### ISSUE TITLE
CSS issue with long abilities list

### ISSUE THREAD

**Issue by PhyDoesStuff** [Xzotl42/arm5e#214]
Once the list of abilities in a section grows large enough, abilities start clipping into the next section. Seen specifically in the General Abilities section at 22 abilities, where the last skill on the list started clipping into/rendering on top of the Academic Abilities section.

![image](https://user-images.githubusercontent.com/17521733/211144026-183356d8-9f58-4bd0-b30b-b892dfe83e07.png)

Breakdown of ability counts by group:
- General: 22
- Academic: 4
- Arcane: 5
- Martial: 1
- Mystery: 1
- Supernatural: 2

I didn't test if similar results could be replicated in the other ability sections, but it's likely.

**Comment by Xzotl42** [comment]
Thank you for the report, this is a known problem which has been fixed on the dev branch.
In the meantime, if you want to get ride of it, you can edit the file in arm5e/css named arm5e.css and change the **collapse** style max-height to an higher value.

.collapse {
  max-height: **2180px**;
  transition-property: all;
  transition-duration: 0.6s;
  transition-timing-function: ease-in-out;
}

Note that it will be overwritten when you update the system again
